// Terminal loader — typed bridge between SvelteKit and the Emscripten WASM module.
//
// The WASM module is loaded from /wasm/market_classifier.js (generated by the WASM
// build preset and copied to apps/web/static/wasm/).  This file is responsible for:
//   - dynamically importing the Emscripten JS glue
//   - signalling readiness to the SvelteKit page
//   - reporting fatal load errors with sanitized messages
//
// The WASM module itself sets data-wasm-status and data-frame-count on document.body
// (see engine/src/main.cpp js_set_wasm_ready / js_increment_frame_count).

export type TerminalStatus = 'loading' | 'ready' | 'error';

interface LoadCallbacks {
	onReady: () => void;
	onError: (message: string) => void;
}

// The Emscripten MODULARIZE=1 factory function signature.
interface EmscriptenModule {
	canvas?: HTMLCanvasElement;
	onRuntimeInitialized?: () => void;
	setStatus?: (text: string) => void;
	locateFile?: (path: string, prefix: string) => string;
}

type EmscriptenFactory = (overrides?: Partial<EmscriptenModule>) => Promise<EmscriptenModule>;

declare global {
	interface Window {
		MarketClassifier?: EmscriptenFactory;
	}
}

const WASM_JS_PATH = '/wasm/market_classifier.js';
const LOAD_TIMEOUT_MS = 30_000;

export function loadTerminal(callbacks: LoadCallbacks): void {
	if (typeof window === 'undefined') {
		// SSR / prerender context — no browser, skip silently
		return;
	}

	const canvas = document.getElementById('canvas') as HTMLCanvasElement | null;
	if (canvas === null) {
		callbacks.onError('Canvas element not found. Terminal cannot start.');
		return;
	}

	let timedOut = false;
	const timeout = setTimeout(() => {
		timedOut = true;
		callbacks.onError('Terminal took too long to load. Check network and browser console.');
	}, LOAD_TIMEOUT_MS);

	// Dynamically import the Emscripten JS glue. Vite will treat this as an
	// external URL (not bundled) because it lives in /static/wasm/.
	const script = document.createElement('script');
	script.src = WASM_JS_PATH;
	script.type = 'text/javascript';

	script.onload = async () => {
		if (timedOut) return;

		const factory = window.MarketClassifier;
		if (typeof factory !== 'function') {
			clearTimeout(timeout);
			callbacks.onError('WASM module did not expose expected factory function.');
			return;
		}

		try {
			await factory({
				canvas,
				// Emscripten locateFile resolves sibling WASM binary relative to the JS glue
				locateFile: (path: string) => `/wasm/${path}`,
				onRuntimeInitialized: () => {
					clearTimeout(timeout);
					if (!timedOut) {
						callbacks.onReady();
					}
				}
			});
		} catch (err: unknown) {
			clearTimeout(timeout);
			if (!timedOut) {
				// Do not forward raw error details — may contain file paths or internal state
				callbacks.onError('Terminal runtime error. See browser console for diagnostics.');
				console.error('[market-classifier] WASM runtime error:', err);
			}
		}
	};

	script.onerror = () => {
		clearTimeout(timeout);
		if (!timedOut) {
			callbacks.onError('Failed to load terminal assets. Check that the WASM build has been run.');
		}
	};

	document.head.appendChild(script);
}
